Changed styling to "jekyll lambda"
oslo-pm/oslo-pm.github.io pull request #1
Opened 2017-09-02 09:32 UTC by jhthorsen

Hey!

I've tried to improve the web page, but at the same time keep it as simple as possible. You can check out the page at http://jekyll.thorsen.pm/. (Let me know if the server is down) (Also, jekyll.thorsen.pm is just a demo page, so you can check it out)

Changes (Compared to http://oslo.pm.org/)

* "Vedtekter" is under http://jekyll.thorsen.pm/statutes/ (http://oslo.pm.org/vedtekter.shtml)
* "Kontakt" is under http://jekyll.thorsen.pm/contact (http://oslo.pm.org/kontakt/)
* "Styre" is under http://jekyll.thorsen.pm/board/ (http://oslo.pm.org/styre.shtml)
* Removed link to http://oslo.pm.org/Oslo.pm.ics (Let's use Meetup instead)

New: 
<img width="400" alt="screen shot 2017-09-02 at 10 43 38" src="https://user-images.githubusercontent.com/45729/29994301-d215a2b2-8fcc-11e7-8358-465ac85fe16d.png">

Old:
<img width="400" alt="screen shot 2017-09-02 at 10 48 57" src="https://user-images.githubusercontent.com/45729/29994303-d6c08034-8fcc-11e7-9caa-7785d0b3129d.png">

2017-09-02 09:49 UTC, marcusramberg commented
Lgtm!

2017-09-02 09:54 UTC, marcusramberg approved these changes

2017-09-02 10:28 UTC, nicomen requested changes
tror kanskje events skygger for meetup, nå ser det ut som det ikke har skjedd noe siden 2013
så kanskje blog bør hete blog, og meetup hete events?

Edit: det er jo likegyldig hva vi til enhver tid bruker som event-håndtering; som bruker vil jeg gjerne finne en Event-knapp som sender meg til der hendelser er listet opp

2017-09-02 10:41 UTC, jhthorsen commented
Jeg har endret menyen i b9682ae.

Angående "ingenting har skjedd siden 2013", så har jeg en annen branch med flere innlegg i, men jeg har også tenkt å lage et issue, hvor vi får i oppdrag å hoste opp gamle referater og andre ting som har skjedd. Jeg har en lokal branch som jeg kan pushe senere med fire "nye" innlegg.

Jeg har andre ideer også, men jeg prøver å holde skopet nede for denne PR'n. Målet med denne er å få en litt mer moderne side, men kanskje enda viktigere flytte oss til en platform hvor vi enkelt kan gjøre forbedringer.

2017-09-03 12:37 UTC, merged

2017-09-03 13:19 UTC, jhthorsen commented
👍